### PR TITLE
Fix @js_str interpolation issues.

### LINKED ISSUE #111: js"..." does not escape dollars correctly
```julia
julia> js"this.\$refs"
WebIO.JSString("this.\\\$refs")
```

whereas the correct thing is I believe `WebIO.JSString("this.\$refs")`.

### PR DESCRIPTION
**Pull request by travigd**
Fixes #111.

Requesting review from @shashi and @piever because writing idiomatic Julia isn't exactly my strong suit.

### CODE REVIEW

**Comment by travigd** [comment]
Thanks @piever !

>There's a basic trick that tends to make these things more readable which is the following. Instead of a manual `iterate_interpolations(s, i=firstindex(s))`, you could do:
```julia
struct Interpolator{S<:AbstractString}
  s::S
end
function Base.iterate(interp::Interpolator, i = firstindex(interp.s))
  s = interp.s
  .... # same code body as you have
end
```
> and then basically you can do `[f(x) for x in Interpolator(str)]` and things like that
or say `Iterators.filter(filter_func, Interpolator(str))` and so on (basically use every function that works on iterators)

File: src/syntax.jl [hunk 1]
```diff
@@ -55,27 +55,100 @@ end
...
+An iterator that yields _interpolation chunks (_i.e._ a string if the chunk was a string literal and
+an `Expr` if the chunk was an interpolation).
+
+# Examples
+"""
+struct Interpolator{S<:AbstractString}
+    s::S
+end
+
+Base.iterate(
```
Comment (piever) [inline src/syntax.jl]: I think this could just be
```julia
Base.iterate(interp::Interpolator, args...) = iterate_interpolations(interp.s, args...)
```

**Comment by travigd** [comment]
It turns out string parsing is hard and Julia does strange™ things when quotes are involved. But I **think** it's good to go now (and @piever your suggestions were incorporated, thank you!).
