### PR TITLE
Fix sending commands to multiple frontends.

### LINKED ISSUE #337: Pushing an observable to multiple clients no longer works in WebIO 0.8.9
With WebIO 0.8.9, opening the same scope through multiple frontends results in only one frontend getting the observable updates. This is breaking the MeshCat.jl tests. 

Here is a MWE:

```julia
using WebIO, Mux, Blink, JSExpr

scope = Scope()

# updates to this update the UI
count = Observable(scope, "count", 1)

onjs(count, # listen on JavaScript
     JSExpr.@js x->this.dom.querySelector("#count").textContent = x)

scope.dom = dom"div"(
    dom"div#count"(string(count[])),
)

@async while true
    count[] += 1
    sleep(1)
end

WebIO.webio_serve(Mux.page("/", req -> scope), 8000)

w = Window()
body!(w, scope)
```

If you comment out the `body!(w, scope)` line and just open `localhost:8000` in your browser, then everything is fine (the counter updates once per second). Likewise, if you comment out the `webio_serve` line, then a `Blink` window opens up and shows the counter updating. But if you keep both lines in, then the Blink window updates but the `localhost:8000` page does not. 

This works correctly with WebIO 0.8.8 but fails with 0.8.9. 

Tested with Blink 0.12.0, Mux 0.7.0, JSExpr 0.5.0.

### PR DESCRIPTION
**Pull request by travigd**
This also reworks the way that new channels are added to a scope to work more
synchronously and avoid some race conditions.

Fixes #337 .

### CODE REVIEW

**Comment by travigd** [comment]
Fixes #337.

**Comment by rdeits** [comment]
Thanks! I can confirm that this fixes the original issue. I'll just need to update the `wait()` implementation in MeshCat to use the new connection pool.

File: src/connection.jl [hunk 1]
```diff
@@ -70,14 +64,12 @@ current task until that is the case. Also processes incoming connections.
 """
 function ensure_connection(pool::ConnectionPool)
     if isempty(pool.connections)
-        wait(pool.new_connections)
-    end
-    while isready(pool.new_connections)
-        push!(pool.connections, take!(pool.new_connections))
+        wait(pool.condition)
```
Comment (shashi) [inline src/connection.jl]: Little tiny race condition possible here if a new condition arrives in between `isempty` and `wait`. This might need a lock, eventually.

File: test/multiple-connections.jl [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+    value = (w) -> @js w document.querySelector("[data-testid=foobar]").innerText
+    @test value(w1) == "initial"
+    @test value(w2) == "initial"
+
+    obs[] = "updated"
+    # Sleep to allow the JS to execute.
+    sleep(0.25)
+    @test value(w1) == "updated"
+    @test value(w2) == "updated"
+end
```
Comment (shashi) [inline test/multiple-connections.jl]: sweet tests!

**Comment by tkoolen** [comment]
Could we ask you guys for a new tag with this fix? CC:@rdeits.
